version: 2

base: &base
  working_directory: ~/Puppeteer-Play
  docker:
    - image: circleci/node:10

jobs:

  test:
    <<: *base
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Combat preparation
          command: docker-compose up -d default
      - run:
          name: Check code quality
          command: docker-compose exec default yarn lint
      - run:
          name: Runs end-to-end tests
          command: docker-compose exec default yarn test

workflows:
  version: 2
  e2e-testing:
    jobs:
      - test
