version: 2

base: &base
  working_directory: ~/Puppeteer-Play
  docker:
    - image: circleci/node:10

jobs:

  test:
    <<: *base
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: Combat preparation
          command: docker-compose up -d default
      - run:
          name: Check code quality
          command: docker-compose exec default yarn lint
      - run:
          name: Runs ui tests
          command: docker-compose exec default yarn ui
      - run:
          name: Runs api tests
          command: docker-compose exec default yarn api
      - run:
          name: Runs benchmarks
          command: docker-compose exec default yarn bench

workflows:
  version: 2
  e2e-testing:
    jobs:
      - test
